apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-yr-store 
spec:
  template:
    spec:
      containers:
      - name: mnist-yr-store
        image: yoorachoi/mnist-netcs:latest
        imagePullPolicy: Always
        command: ["python3", "train-pytorch.py"]
        volumeMounts:
        - mountPath: "/model_storage"
          name: yr-pv-store
      restartPolicy: Never
      nodeSelector:
        key: edges
      volumes:
      - name: yr-pv-store
        persistentVolumeClaim:
          claimName: yr-pv-claim
  backoffLimit: 0
