apiVersion: v1
kind: PersistentVolume
metadata:
  name: yr-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: [your-local-path-to-storage]/storage

