apiVersion: batch/v1
kind: Job
metadata:
  name: handson-04
spec:
  template:
    spec:
      containers:
      - name: ml
        image: !IMAGE
        imagePullPolicy: Always
        command: ["python", "-u", "train.py"]
        volumeMounts:
        - mountPath: "/model_hp/"
          name: model-hp
      restartPolicy: Never
      nodeSelector:
        role: train-cpu
      volumes:
      - name: model-hp
        configMap:
          name: model-hp
  backoffLimit: 0

