apiVersion: v1
kind: Service
metadata:
  name: argo-ui
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
  selector:
    app: argo-ui
