apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1000Gi
  storageClassName: nfs-storage
  nfs:
    path: {{ .Values.nfsServerPath }}
    server: {{ .Values.nfsServer }}
  persistentVolumeReclaimPolicy: Delete

