apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-pytorch-yr 
spec:
  template:
    spec:
      containers:
      - name: mnist-pytorch-yr
        image: yoorachoi/minst-netcs:latest
        imagePullPolicy: IfNotPresent
        command: ["python3", "train.py"]
        args: ['5', 'softmax', '0.5']
      restartPolicy: Never
      nodeSelector:
        key: edges

  backoffLimit: 0

