apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-pytorch-yr 
spec:
  template:
    spec:
      containers:
      - name: mnist-netcs
        image: yoorachoi/mnist-netcs:latest
        imagePullPolicy: IfNotPresent
        command: ["python3", "train-pytorch.py"]
        #args: ['5', 'softmax', '0.5']
        #terminationMessagePath: "/tmp/my-log"
      restartPolicy: Never
      nodeSelector:
        key: edges

  backoffLimit: 0

