apiVersion: batch/v1
kind: Job
metadata:
  name: train-mnist 
spec:
  template:
    spec:
      containers:
      - name: ml
        image: yoorachoi/train-mnist-keras:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "train.py"]
        args: ['5', 'softmax', '0.5']
      restartPolicy: Never
      nodeSelector:

  backoffLimit: 0

